language: node_js

before_install:
- gem install compass

install:
- npm install --quiet -g grunt-cli
- npm install --quiet

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start &
- sleep 3

script:
- grunt release
- grunt coveralls

cache:
  directories:
  - node_modules
  - bower_components
